#!/usr/bin/env python3
import sys

try:
    import libyang
    import yangvoodoo
    from yangvoodoo.Common import Utils

    libyang.util.InvalidSchemaOrValueError
except ImportError:
    print("")
    print("WARNING")
    print("=======")
    print("")
    print("Unable to import the forked libyang-cffi library.")
    print(" see https://github.com/allena29/python-yang-voodoo/blob/master/INSTALL.md.")
    print("")
    print("")
    raise

try:
    import jinja2
    import dictdiffer
except ImportError:
    print("")
    print("WARNING")
    print("=======")
    print("")
    print("Missing python libraries please 'pip install -r requirements.txt' or pull the")
    print("latest docker image.")
    print("")
    print("")
    raise


# Using Stub backend
session = yangvoodoo.DataAccess()
yangmodel = "integrationtest"
if len(sys.argv) == 2:
    yangmodel = sys.argv[1]
session.connect(yangmodel, yang_location="yang")
session.add_module("foreign")
root = session.get_node()
yang = root._context.schema
yangctx = root._context.schemactx
context = root._context
backend = root._context.dal

import IPython

yangvoodoo.DataAccess._welcome()
print("YANGVOOODOO Version %s" % (session.__version__))
print("")
IPython.embed(display_banner=False)
