#!/usr/bin/env python3
import yangvoodoo
from yangvoodoo.Common import Utils

try:
    import jinja2
    from lxml import etree
    import dictdiffer
except ImportError as err:
    print("")
    print("WARNING")
    print("=======")
    print("")
    print("Missing python libraries please 'pip install -r requirements.txt' or pull the")
    print("latest docker image.")
    print("")
    print("")
    raise

print("Using stub (libyang) data abstraction layer")
print(" - YANG operations on data (when's, must's and leafref paths not implemented)")
print("   SCHEMA based validation will still occur.")
print()

# Using Stub backend
import yangvoodoo.stublydal
stub = yangvoodoo.stublydal.StubLyDataAbstractionLayer()
session = yangvoodoo.DataAccess(data_abstraction_layer=stub)

session.connect('integrationtest', yang_location='yang')
root = session.get_node()
yang = root._context.schema
yangctx = root._context.schemactx
context = root._context
backend = root._context.dal.data_abstraction_layer
ninja = yangvoodoo.TemplateNinja.TemplateNinja()

import IPython

yangvoodoo.DataAccess._welcome()
print('YANGVOOODOO Version %s' % (session.__version__))
print('')
IPython.embed(display_banner=False)
