#!/bin/sh

docker images &>/dev/null
container="yangvoodoo"
image="allena29/yangvoodoo:devel"
if [ $? = 0 ]
then
  echo "Docker is running...."
else
  echo "Docker daemon is not running!"
  exit 1;
fi

pwd=`pwd`
echo "Running in local dir $pwd" >/dev/stderr
docker run --name=$container -i -d -v $pwd:/working:rw $image /working/start-in-docker.sh
docker exec -i -t $container /bin/bash
