#!/usr/bin/python3
import IPython
import yangvoodoo
import sysrepo as sr
import libyang

session = yangvoodoo.DataAccess(remote_log=True)
session.connect()
root = session.get_root('integrationtest')

print('Objects Ready to Play with')
print('--------------------------')
print('root << node based access')
print('   ', root)
backend = session.session
print('sesssion << xpath based access (this is dal on root._context)')
print('   ', session)
print('backend << sysrepo session (this is what session wraps up for us)')
print('   ', backend)

IPython.embed(display_banner=False)
