#!/usr/bin/python3
import IPython
import yangvoodoo
import yangvoodoo.stubdal
import libyang


# Using Stub backend
# stub = yangvoodoo.stubdal.StubDataAbstractionLayer()
# session = yangvoodoo.DataAccess(remote_log=True, data_abstraction_layer=stub)

# Using Sysrepo backend
session = yangvoodoo.DataAccess(remote_log=True, data_abstraction_layer=stub)


session.connect()
root = session.get_root('integrationtest')
backend = session.session
yang = root._context.schema
yangctx = root._context.schemactx

print('Objects Ready to Play with')
print('--------------------------')
print('root << node based access')
print('   ', root)
print('sesssion << xpath based access (this is dal on root._context)')
print('   ', session)
print('backend << sysrepo session (this is what session wraps up for us)')
print('   ', backend)
print('yang    << libyang instance')
print('yangctx << libyang context instance')
print('   ', yangctx)
IPython.embed(display_banner=False)
